### ISSUE TITLE
Too few issues

### ISSUE THREAD

**Issue by wei2912** [Subsentient/wz2100legacy#1]
I feel that I'll be kicked for this, but here goes:

there are just too few issues. With little issues it's not easy for other developers (such as me)to contribute to the project. With issues, we can pick on an issue and start working on it, obtain information from other users and many more. Legacy would be much more active.

Once there are more than 5 issues I'll close this. Don't say this is bug free - nothing is.

**Comment by Subsentient** [comment]
All my code is bug free, because I wrote it. :^3

**Comment by wei2912** [comment]
But you merely wrote 1% :) there's quite some crap in the other 99%. furthermore there's no such thing as bug free, because we have no idea if something _is_ completely bug free. we only know if something is not known to have bugs, which is an entirely different matter.

**Comment by wei2912** [comment]
This issue is redundant. Derp.

**Comment by Subsentient** [comment]
The codebase is unreadable vomit. That's an issue. Hundreds of .c files of issue.

**Comment by wei2912** [comment]
Okay, creating an issue for that.

**Comment by wei2912** [comment]
Reopening this issue because it's still an issue.

**Comment by Subsentient** [comment]
Restating my code was inspired by god because the issue is reopened.

**Comment by wei2912** [comment]
This appears to be no longer an issue, so closing it (once more).
