### ISSUE TITLE
IRC-style nick highlight & autocompletion

### ISSUE THREAD

**Issue by wei2912** [Subsentient/wz2100legacy#10]
Nick highlight.

Map/nick autocompletion.

**Comment by Subsentient** [comment]
This is doable.

**Comment by wei2912** [comment]
I hope it is :)

**Comment by Subsentient** [comment]
Closing. It has been implemented in commit https://github.com/Subsentient/wz2100legacy/commit/66fbe6bfa94db2fe4cb95e1edceb3e1f4b911dcd. It only works for in-game chat, but we still got !beep for getting people's attention.
