### ISSUE TITLE
Spectator support for 2.3 codebase Legacy

### ISSUE THREAD

**Issue by wei2912** [Subsentient/wz2100legacy#6]
We'll need spectator support, just as how Legacy Beta 1 was like.

**Comment by Subsentient** [comment]
It would be easy to implement, assuming I wish to keep the current
netcode, which I really don't. The interface and effects portion would be
easy, but synchronizing with players on a protocol that will likely
change, well, not so much.

**Comment by wei2912** [comment]
With the new protocol, I think spectator support should be easier to implement.

**Comment by Subsentient** [comment]
It will be, but the protocol must be implemented before spectator support. I have every intent of implementing spectator support mind you, I just want to get things done in the right order.

**Comment by Subsentient** [comment]
Spectator support has been implemented with commit https://github.com/Subsentient/wz2100legacy/commit/5ce9348820b11f88c6f3d01499d1eb7e4b5f0ba2. Closing.
